"""Init db

Revision ID: 01eebafac9fc
Revises: 
Create Date: 2019-03-27 20:47:21.461311

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '01eebafac9fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=30), nullable=True),
                    sa.Column('email', sa.String(length=254), nullable=True),
                    sa.Column('username', sa.String(length=20), nullable=True),
                    sa.Column('_password_hash', sa.String(length=128), nullable=True),
                    sa.Column('website', sa.String(length=255), nullable=True),
                    sa.Column('bio', sa.String(length=120), nullable=True),
                    sa.Column('location', sa.String(length=50), nullable=True),
                    sa.Column('member_since', sa.DateTime(), nullable=True),
                    sa.Column('confirmed', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
