"""user add ava_raw

Revision ID: 051edf0d0ac2
Revises: cf1be571dda8
Create Date: 2019-05-01 15:52:53.854140

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '051edf0d0ac2'
down_revision = 'cf1be571dda8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.add_column(sa.Column('avatar_raw', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('avatar_raw')
    # ### end Alembic commands ###
