"""add photo flag

Revision ID: 2247c41acec7
Revises: 8eac977c6ed7
Create Date: 2019-04-16 17:37:01.932107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2247c41acec7'
down_revision = '8eac977c6ed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo') as batch_op:
        batch_op.add_column(sa.Column('flag', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo') as batch_op:
        batch_op.drop_column('flag')
    # ### end Alembic commands ###
