"""add avatars

Revision ID: 8eac977c6ed7
Revises: bc1a39a614d4
Create Date: 2019-04-03 21:24:59.650659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eac977c6ed7'
down_revision = 'bc1a39a614d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.add_column(sa.Column('avatar_l', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('avatar_m', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('avatar_s', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('avatar_s')
        batch_op.drop_column('avatar_m')
        batch_op.drop_column('avatar_l')
    # ### end Alembic commands ###
