"""add comment

Revision ID: 9ecbd3d3dfbe
Revises: 93a5cf99be66
Create Date: 2019-04-18 22:51:14.484154

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9ecbd3d3dfbe'
down_revision = '93a5cf99be66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('body', sa.Text(), nullable=True),
                    sa.Column('flag', sa.Integer(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.Column('photo_id', sa.Integer(), nullable=True),
                    sa.Column('author_id', sa.Integer(), nullable=True),
                    sa.Column('replied_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_comment_author_id_user')),
                    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], name=op.f('fk_comment_photo_id_photo')),
                    sa.ForeignKeyConstraint(['replied_id'], ['comment.id'], name=op.f('fk_comment_replied_id_comment')),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_comment_timestamp'), 'comment', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_timestamp'), table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###
