"""add table photo and ...

Revision ID: bc1a39a614d4
Revises: ef63f70c1979
Create Date: 2019-04-01 19:18:34.016169

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bc1a39a614d4'
down_revision = 'ef63f70c1979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('filename', sa.String(length=64), nullable=True),
                    sa.Column('filename_m', sa.String(length=64), nullable=True),
                    sa.Column('filename_s', sa.String(length=64), nullable=True),
                    sa.Column('description', sa.String(length=500), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.Column('author_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_photo_author_id_user')),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    # ### end Alembic commands ###
