"""create notifications

Revision ID: cf1be571dda8
Revises: cc1a3828f629
Create Date: 2019-04-30 16:53:53.094792

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cf1be571dda8'
down_revision = 'cc1a3828f629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('message', sa.Text(), nullable=True),
                    sa.Column('is_read', sa.Boolean(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.Column('receiver_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'],
                                            name=op.f('fk_notification_receiver_id_user')),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_notification_timestamp'), 'notification', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_timestamp'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
