"""photo add can_comment

Revision ID: e75fd97a2606
Revises: 9ecbd3d3dfbe
Create Date: 2019-04-18 23:00:06.305635

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e75fd97a2606'
down_revision = '9ecbd3d3dfbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo') as batch_op:
        batch_op.add_column(sa.Column('can_comment', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo') as batch_op:
        batch_op.drop_column('can_comment')
    # ### end Alembic commands ###
