"""add rbac models

Revision ID: ef63f70c1979
Revises: 01eebafac9fc
Create Date: 2019-03-30 18:29:42.391367

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ef63f70c1979'
down_revision = '01eebafac9fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=20), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name', name=op.f('uq_permission_name'))
                    )
    op.create_table('role',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=20), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name', name=op.f('uq_role_name'))
                    )
    op.create_table('roles_permissions',
                    sa.Column('role_id', sa.Integer(), nullable=True),
                    sa.Column('permission_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'],
                                            name=op.f('fk_roles_permissions_permission_id_permission')),
                    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_roles_permissions_role_id_role'))
                    )
    with op.batch_alter_table('user') as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(op.f('fk_user_role_id_role'), 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_constraint(op.f('fk_user_role_id_role'), type_='foreignkey')
        batch_op.drop_column('role_id')
    op.drop_table('roles_permissions')
    op.drop_table('role')
    op.drop_table('permission')
    # ### end Alembic commands ###
